export const customer=[
        {logo:'/Logos/Users.png',
        name:'Users',
        id:1,},
        {logo:'/Logos/Guarantors.png',
        name:'Guarantors',
        id:2},
        {logo:'/Logos/Loans.png',
        name:'Loans',
        id:3},
        {logo:'/Logos/Decision.png',
        name:'Decision Models',
        id:4},
        {logo:'/Logos/Saving.png',
        name:'Savings',
        id:5},
        {logo:'/Logos/Req.png',
        name:'Loan Request',
        id:6},
        {logo:'/Logos/whitelist.png',
        name:'Whitelist',
        id:7},
        {logo:'/Logos/karma.png',
        name:'Karma',
        id:8}
        
    ]
    export const business=[
        {logo:'/Logos/brief.png',
        name:'Organization',
        id:1,},
        {logo:'/Logos/Loans.png',
        name:'Loan Products',
        id:2},
        {logo:'/Logos/Saving.png',
        name:'Savings Products',
        id:3},
        {logo:'/Logos/fees.png',
        name:'Fees and Charges',
        id:4},
        {logo:'/Logos/transaction.png',
        name:'Transactions',
        id:5},
        {logo:'/Logos/galaxy.png',
        name:'Services',
        id:6},
        {logo:'/public/Logos/Users.png',
        name:'Service Account',
        id:7},
        {logo:'/Logos/settlement.png',
        name:'Settlements',
        id:8},
        {logo:'/Logos/report.png',
        name:'Reports',
        id:9}
        
    ]
    export const settings=[
        {logo:'/Logos/prefrence.png',
        name:'Preferences',
        id:1,},
        {logo:'/Logos/fees.png',
        name:'Fees and Pricing',
        id:2},
        {logo:'/Logos/audit.png',
        name:'Audit Logs',
        id:3},
        {logo:'/Logos/tire.png',
        name:'Systems Messages',
        id:4}
        
    ]

    export const data=[
        {logo:'/Logos/usericon.png',
        name:'USERS',
        id:1,
        number:2453},
        {logo:'/Logos/active.png',
        name:'ACTIVE USERS',
        id:2,
        number:2453},
        {logo:'/Logos/userloan.png',
        name:'USERS WITH LOANS',
        id:3,
        number:12453},
        {logo:'/Logos/loansavings.png',
        name:'USERS WITH SAVINGS',
        id:4,
        number:102453}
    ]